### ISSUE TITLE
`spike login` should inform user to run `spike init` first if the system is not initialized.

### ISSUE THREAD

**Issue by v0lkan** [spiffe/spike#37]
When you do a `spike get` w/o initialization you get a warning to run `spike init`.

However, that does not happen for `spike login`.

It should.

dump:

```
volkan@spike:~/.spike$ spike get /db
>>>>>>>>>>>>>>>Posting to https://localhost:8553/v1/init?action=check
{"time":"2024-11-15T18:09:12.541849955-08:00","level":"INFO","msg":"post","path":"https://localhost:8553/v1/init?action=check"}
Please initialize SPIKE with `spike init` first.
volkan@spike:~/.spike$ spike login
Enter admin password: 
{"time":"2024-11-15T18:09:28.127624512-08:00","level":"INFO","msg":"post","path":"https://localhost:8553/v1/login?action=admin-login"}
Failed to login:
login: I am having problem sending the request
unauthorized
volkan@spike:~/.spike$ 
```

**Comment by yigithankarabulut** [comment]
Could you assign to me?

**Comment by kfox1111** [comment]
spike login may be useful later for login via oidc provider. But I agree, spike shouldn't ever handle a password for its own use. just to store/retrieve for the user.

**Comment by yigithankarabulut** [comment]
Thanks for the information, good to know this approach. I will be interested in other issues.

**Comment by v0lkan** [comment]
Sure thing; I'll go through the backlog and open up further "good first issues".

Since the project is evolving really fast, it's more like a Cambrian soup — we decide to do something; then realize there are other better ways of doing it. Archive some of the code… create new ones… rinse and repeat :) 

Feel free to reach out at any time.

**Comment by v0lkan** [comment]
Closing for now…

I'll do some bookkeeping tonight (on live stream if you wanna join), and add other relevant issues.
